# Expression generated by update.sh; do not edit it by hand!
{ stdenv, callPackage, ... }@args:

let
  pname = "brave-origin";
  version = "1.91.133";

  allArchives = {
    aarch64-linux = {
      url = "https://github.com/brave/brave-browser/releases/download/v1.91.133/brave-origin-beta_1.91.133_arm64.deb";
      hash = "sha256-G+GfDRiuQ4hhdZbM4jnpTENzhhiK7LXsQCnL+eEylVY=";
    };
    x86_64-linux = {
      url = "https://github.com/brave/brave-browser/releases/download/v1.91.133/brave-origin-beta_1.91.133_amd64.deb";
      hash = "sha256-Qh09IIO0BOXdaVwigiUF21TCx5ZVsNPuC79mr9DTypg=";
    };
    aarch64-darwin = {
      url = "https://github.com/brave/brave-browser/releases/download/v1.91.133/brave-origin-v1.91.133-darwin-arm64.zip";
      hash = "sha256-P4rLGrhJyxipnOHC1OK31+l73mXmvBvQewRhUBBZ5BI=";
    };
    x86_64-darwin = {
      url = "https://github.com/brave/brave-browser/releases/download/v1.91.133/brave-origin-v1.91.133-darwin-x64.zip";
      hash = "sha256-k6staU4N94hNZw48NcqLuicInmiKmTXcSWMCWO3PjL0=";
    };
  };

  archive =
    if builtins.hasAttr stdenv.system allArchives then
      allArchives.${stdenv.system}
    else
      throw "Unsupported platform.";

in
callPackage ./make-brave.nix (removeAttrs args [ "callPackage" ]) (
  archive
  // {
    inherit pname version;
  }
)
