#!/usr/bin/env nix-shell
#!nix-shell -i bash -p curl gnused nix jq

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

RELEASE_JSON="$(curl --fail -s ${GITHUB_TOKEN:+-u ":$GITHUB_TOKEN"} "https://api.github.com/repos/brave/brave-browser/releases" | jq '[.[] | select(.name | startswith("Beta"))][0]')"
latestVersion="$(echo "$RELEASE_JSON" | jq -r '.tag_name' | sed 's/^v//')"

urlAarch64="$(echo "$RELEASE_JSON" | jq -r '.assets[] | select(.name | test("brave-origin-beta_.*_arm64\\.deb$")) | .browser_download_url')"
urlAmd64="$(echo "$RELEASE_JSON" | jq -r '.assets[] | select(.name | test("brave-origin-beta_.*_amd64\\.deb$")) | .browser_download_url')"
urlAarch64Darwin="$(echo "$RELEASE_JSON" | jq -r '.assets[] | select(.name | test("brave-origin-v.*-darwin-arm64\\.zip$")) | .browser_download_url')"
urlAmd64Darwin="$(echo "$RELEASE_JSON" | jq -r '.assets[] | select(.name | test("brave-origin-v.*-darwin-x64\\.zip$")) | .browser_download_url')"

hashAarch64="$(nix-hash --to-sri --type sha256 "$(nix-prefetch-url --type sha256 "$urlAarch64")")"
hashAmd64="$(nix-hash --to-sri --type sha256 "$(nix-prefetch-url --type sha256 "$urlAmd64")")"
hashAarch64Darwin="$(nix-hash --to-sri --type sha256 "$(nix-prefetch-url --type sha256 "$urlAarch64Darwin")")"
hashAmd64Darwin="$(nix-hash --to-sri --type sha256 "$(nix-prefetch-url --type sha256 "$urlAmd64Darwin")")"

cat > "$SCRIPT_DIR/package.nix" << EOF
# Expression generated by update.sh; do not edit it by hand!
{ stdenv, callPackage, ... }@args:

let
  pname = "brave-origin";
  version = "${latestVersion}";

  allArchives = {
    aarch64-linux = {
      url = "${urlAarch64}";
      hash = "${hashAarch64}";
    };
    x86_64-linux = {
      url = "${urlAmd64}";
      hash = "${hashAmd64}";
    };
    aarch64-darwin = {
      url = "${urlAarch64Darwin}";
      hash = "${hashAarch64Darwin}";
    };
    x86_64-darwin = {
      url = "${urlAmd64Darwin}";
      hash = "${hashAmd64Darwin}";
    };
  };

  archive =
    if builtins.hasAttr stdenv.system allArchives then
      allArchives.\${stdenv.system}
    else
      throw "Unsupported platform.";

in
callPackage ./make-brave.nix (removeAttrs args [ "callPackage" ]) (
  archive
  // {
    inherit pname version;
  }
)
EOF
